import = ["~/.config/alacritty/dracula.toml", "~/.config/alacritty/font.toml"]

[window.padding]
x = 2
y = 2

[font]
size = 10

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"
